# Generated by Django 5.0.6 on 2024-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="priorities",
        ),
        migrations.AddField(
            model_name="lead",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=50,
            ),
        ),
    ]
