# Generated by Django 5.0.6 on 2024-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0002_remove_lead_priorities_lead_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_to_client",
            field=models.BooleanField(default=False),
        ),
    ]
